### PR TITLE
Add VL53L1X VL53L4CD/X VL6180X

### PR DESCRIPTION
**Pull request by tyeth**
~~This updates the addresses available for the VL53L0X.~~

~~Also adds new unpublished definitions for:
VL53L1X
VL53L4CD
VL53L4CX
VL6180X~~

Breaking into tasks
- [x] VL53L1X
- [x] VL53L4CD
- [x] VL53L4CX
- [x] VL6180X

### CODE REVIEW

**Comment by brentru** [comment]
@tyeth  What's the status on this PR? Are we waiting for something?

**Comment by tyeth** [comment]
Splitting this out, after chatting with Limor on Friday, will do the VL6180X first in #202

**Comment by tyeth** [comment]
VL53L1X closed by #209

**Comment by tyeth** [comment]
VL53L4CD closed by https://github.com/adafruit/Wippersnapper_Components/pull/210, tested as part of https://github.com/adafruit/Adafruit_Wippersnapper_Arduino/pull/550, held up by funhouse noota changes to io-rails before we can do a new release.

**Comment by tyeth** [comment]
No longer held up, all released.
VL53L4CX to follow

**Comment by tyeth** [comment]
In main, closed in firmware repo by https://github.com/adafruit/Adafruit_Wippersnapper_Arduino/pull/564

**Pull request closed without merging**
