### PR TITLE
Sensor Precision

### PR DESCRIPTION
**Pull request by lorennorman**

### CODE REVIEW

**Comment by TheGodMotherG** [comment]
This would be amazing to have

**Comment by lorennorman** [comment]
@TheGodMotherG Glad you're interested! Can you say more about what would be amazing? Which sensor would you like this for, and what precision (number of decimal places) would you set for it?

**Comment by brentru** [comment]
@lorennorman  is this pull request stale?

**Comment by lorennorman** [comment]
@brentru Yeah seems so. The feature is still outstanding and worth doing, but I haven't seen any actual requests for different precisions on different components, yet. Nothing special in this PR tho, gonna close it and we can make a new one if a precision use case shows up.

**Pull request closed without merging**
