### PR TITLE
add sht3x and lowercase SHT40

### PR DESCRIPTION
**Pull request by tyeth**
This adds the SHT30-D / SHT31-DIS / SHT35-D. 
It supports 0x44 and 0x45, and the product image is from https://www.adafruit.com/product/2857.
I've never seen or heard of the SHT31-ARP which is the analog pin version of the sensor, but it requires different setup although the driver is there, so not included as not I2C.

### CODE REVIEW

**Comment by brentru** [comment]
@tyeth  Does this component PR tie in with https://github.com/adafruit/Adafruit_Wippersnapper_Arduino/pull/325?

**Comment by tyeth** [comment]
Yes it does. I tested the 40/3X code by replacing the 40 with the 3x code, and testing the same with the alternative i2c address. Then moved to separate driver.

**Comment by brentru** [comment]
@lorennorman  This pull request is ready. It lower-cases an existing sensor (may need to be deleted from DB). Let me know how to proceed. Thanks!

**Review by brentru — APPROVED** [review]

**Comment by lorennorman** [comment]
great work, folks! I'll do the work on prod and then merge this myself, i plan to do this by the end of the day today.

**Comment by lorennorman** [comment]
Ok, this one has been updated in production and should be working correctly under the new lowercased string. Do please give it a test for me!

**Comment by tyeth** [comment]
Yeah looks good, I got no noticeable impact on my existing SHT40 feeds + sensors. Just added an SHT3X at default address 0x44 (worked fine) then removed and changed address, loved the fact it chose the second port 0x45 when that was all that's connected. Seems to be working fine. I've added an SHT40 too, but I'm running alternative firmware that checks both cases (upper/lower) so will retest when v50 is released.

**Pull request merged**
