### PR TITLE
Add definition for Sensirion SGP30

### PR DESCRIPTION
**Pull request by tyeth**
@brentru @lorennorman 
There's a minor hiccup:
The schema for the i2c component subtypes doesn't have TVOC, but it is included in the Adafruit_Sensor repo, so I assume that's the correct value to use, along with eco2 for the SGP30. The i2c component schema will need updating to add the `tvoc` type

### CODE REVIEW

**Comment by lorennorman** [comment]
@tyeth perfect, thanks for this work and the note.

I've just added a commit with the `tvoc` sensorType added, that validation step should pass now. I'm going to go look in our other repos and see if there's other places i need to account for it.

@brentru I was looking at this list to see what all sensor types are in there:
https://github.com/adafruit/Adafruit_Sensor#standardised-si-values-for-sensors_event_t

We don't seem to be one-for-one with that list, is that expected? Or should we try to match that closely?

**Comment by lorennorman** [comment]
Other places to update:
- web frontend (me)
- mqtt broker (me)
- [protocol buffers](https://github.com/adafruit/Wippersnapper_Protobuf/blob/c00e79b1b8c513200e8d94395919d62133fc529d/proto/wippersnapper/i2c/v1/i2c.proto#L153-L188) (@brentru)
- [ws arduino](https://github.com/adafruit/Adafruit_Wippersnapper_Arduino/blob/f2bb070674deac8f3852be228cca6a7ddc44caa8/src/wippersnapper/i2c/v1/i2c.pb.h#L25-L60) (@tyeth or @brentru)

**Comment by tyeth** [comment]
Seen the file size image issue, woops forgot that bit, only remembered a limit for GIFs, will fix in morning

**Comment by tyeth** [comment]
@lorennorman I no longer have the ability to rerun due to your commit touching restricted files, but should be fine.

**Comment by brentru** [comment]
@lorennorman @tyeth  Enumerated type for TVOC has been added within WipperSnapper_Protobuf and wrappers have been compiled and merged into WipperSnapper_Arduino.

**Review by ladyada — COMMENTED** [review]
lgtm

**Pull request merged**
