### PR TITLE
Add UART Component Type

### PR DESCRIPTION
**Pull request by brentru**
Adding a new component type, UART. These components have a configurable baud rate and a `subcomponents` array like i2c sensor components.

Related: 
https://github.com/adafruit/Wippersnapper_Protobuf/pull/129

### CODE REVIEW

**Review by lorennorman — APPROVED** [review]
This looks great. I see you worked through some failures on the new Action before getting it to pass, so that gives me warm fuzzies.

I wouldn't merge this until other parts of the puzzle are in place, the web/admin importer will likely fail on this, for instance.

**Review by tyeth — COMMENTED** [review]
Looks good to me. Assuming I shouldn't merge things unless a) told to, and b) reviewed by someone other than myself.

mental note to self to cleanup the readme at some point as the tables / formatting needs work, has a slight wince at the mention of I2C sensor types in the uart schema :)

**Comment by brentru** [comment]
Yeah, we're holding off on merging.

**Review by lorennorman — COMMENTED** [review]
Looks good! 👍🏽 

No merging until I write and test the importer against this branch, is it ready for that?

**Comment by brentru** [comment]
@lorennorman  Let's wait until we have:

* UART Component (finalized)
* Boards UART change (not finalized yet)
* Protobuf for UART (almost final, working on diagram)

**Pull request merged**
