### PR TITLE
Add SCD-30 NDIR CO2 i2c sensor

### PR DESCRIPTION
**Pull request by ckostovny**
Adding Adafruit SCD-30 - NDIR CO2 Temperature and Humidity Sensor, looks like i2c driver is already created for this one?

### CODE REVIEW

**Comment by brentru** [comment]
@ckostovny There _is_ an I2C driver (https://github.com/adafruit/Adafruit_Wippersnapper_Arduino/blob/main/src/components/i2c/drivers/WipperSnapper_I2C_Driver_SCD30.h), but it's untested.

Are you interested in taking a look at the driver as well?

**Review by brentru — APPROVED** [review]
Files look good and pass validation.

**Comment by ckostovny** [comment]
> @ckostovny There _is_ an I2C driver (https://github.com/adafruit/Adafruit_Wippersnapper_Arduino/blob/main/src/components/i2c/drivers/WipperSnapper_I2C_Driver_SCD30.h), but it's untested.
> 
> Are you interested in taking a look at the driver as well?

I don't understand C, but I do have an SCD30 I could test with.

**Comment by brentru** [comment]
Ok, let's see if it'll "just work". I can always fix up the driver if you experience bugs. Could you report the result on this issue (I'll leave it open)?

**Comment by brentru** [comment]
Should be live now :)

**Comment by ckostovny** [comment]
Looks like its working, I see data in the stream:
2022/04/14 1:29PMAdafruit ESP32-S2 FeatherSCD30: Temperature 27.445066452026367
2022/04/14 1:29PMAdafruit ESP32-S2 FeatherSCD30: Relative Humidity 35.95929718017578
2022/04/14 1:29PMAdafruit ESP32-S2 FeatherSCD30: CO2 799.2197875976562
2022/04/14 1:34PMAdafruit ESP32-S2 FeatherSCD30: Temperature 25.585973739624023
2022/04/14 1:34PMAdafruit ESP32-S2 FeatherSCD30: Relative Humidity 39.836612701416016
2022/04/14 1:34PMAdafruit ESP32-S2 FeatherSCD30: CO2 955.259033203125
thanks @brentru!

**Comment by brentru** [comment]
Cool! I'll close out the issue

**Pull request merged**
