### PR TITLE
Sht40

### PR DESCRIPTION
**Pull request by TheGodMotherG**
sht40 test

### CODE REVIEW

**Comment by brentru** [comment]
Hi @TheGodMotherG! Thanks for adding a definition for this sensor.


Are you also planning to add the required I2C Component Driver (https://learn.adafruit.com/how-to-add-a-new-component-to-adafruit-io-wippersnapper/adding-an-i2c-component-driver) to WipperSnapper Arduino? It should be similar to the AHT20 driver which already exists in the firmware.

**Comment by TheGodMotherG** [comment]
Lmao I’m brand new to this but I need the chip to work I will give it my
best shoot. Because you guys said later in the summer but I need it asap
so. Yes I will be attempting it

**Comment by TheGodMotherG** [comment]
Ok i did the driver hope it is what you are looking for to add it to the IO platform

**Comment by brentru** [comment]
Going to merge this so it's usable for testing in Adafruit IO (you should see the SHT40 component on IO). 

Let's continue the convo over on https://github.com/adafruit/Adafruit_Wippersnapper_Arduino/pull/266/ so we can test!

**Pull request merged**
