### PR TITLE
add SEN55 component definiton and image

### PR DESCRIPTION
**Pull request by tyeth**
Addresses #103 
Added in an unpublished state as part of the new dev/testing workflow

### CODE REVIEW

**Comment by brentru** [comment]
@lorennorman  This PR adds two new sensor types - could you please review and suggest (if any) feedback to Tyeth? Thank you!

**Comment by lorennorman** [comment]
@brentru this PR itself looks fine, but it's using new sensor types that we need to propagate through our codebases.

1. i added `voc-index` and `nox-index` to sensors.json and the i2c schema, take a look and see if the `displayName`s are appropriate.
2. we need to add to these to the Arduino code, right?
3. i need to add to the web and broker codebases as well

If all that is true, then this PR is waiting on the rest to get done and deployed.

**Comment by lorennorman** [comment]
@tyeth FYI, no need to force-push most of the time, merge commits are totally fine/expected here! (Your force push happened to land while i was working and conflicted with what i was up to.)

**Comment by tyeth** [comment]
ah so sorry, got in the rebase habit and saw the protobuf come in

**Comment by brentru** [comment]
> i added voc-index and nox-index to sensors.json and the i2c schema, take a look and see if the displayNames are appropriate.

This looks OK to me!

> we need to add to these to the Arduino code, right?

Correct, this has been addressed by @tyeth within WS Arduino and Adafruit Sensor

> i need to add to the web and broker codebases as well

@lorennorman  Let me know here when this is done and I'll start reviewing the other PRs

**Comment by lorennorman** [comment]
@brentru ok working those up now, won't take long.

In the WipperSnapper view, what should the voc and nox readouts say? For instance, fahrenheit template is `${v}°F`. Is there a preferred symbol or shorthand for "VOC/NOX Index"?

**Comment by lorennorman** [comment]
These also need to be added to the protobufs repo and merged so I can update the broker's protobuf wrappers (guessing you'll be doing this for the arduino side as well):
https://github.com/adafruit/Wippersnapper_Protobuf/blob/master/proto/wippersnapper/i2c/v1/i2c.proto#L185

**Comment by tyeth** [comment]
> In the WipperSnapper view, what should the voc and nox readouts say? For instance, fahrenheit template is `${v}°F`. Is there a preferred symbol or shorthand for "VOC/NOX Index"?

No symbol probably,  to match the lack of units in an index. 
If easy I'd have the unit as `${$v}VOC` or NOx accordingly otherwise none.

 Maybe we could use some clever symbol, but couldn't see one instantly

**Comment by lorennorman** [comment]
Ok, made that template update, thanks @tyeth.

@brentru This is all good now, I just need the protobuf wrappers updated to include these 2 types then I can deploy them to production.

**Comment by brentru** [comment]
>  I just need the protobuf wrappers updated to include these 2 types then I can deploy them to production.

Done, see https://github.com/adafruit/Wippersnapper_Protobuf/pull/124

**Review by lorennorman — APPROVED** [review]
This PR looks good to me. I've just deployed support for these component types to production, this is ready to merge and get imported to production for testing.

**Comment by brentru** [comment]
Merging to allow testing on https://github.com/adafruit/Adafruit_Wippersnapper_Arduino/pull/386

**Pull request merged**
