### PR TITLE
Add VL53L4CD I2C Component

### PR DESCRIPTION
**Pull request by afp316**
This pull request adds the Adafruit VL53L4CD Time of Flight Distance Sensor Breakout to WipperSnapper_Components

Product URL: https://www.adafruit.com/product/5396

### CODE REVIEW

**Comment by ladyada** [comment]
@afp316 do you have a PR for https://github.com/adafruit/Adafruit_Wippersnapper_Arduino to add the sensor managing code?

**Comment by afp316** [comment]
I'm currently working on adding the I2C component driver and plan to submit
a PR for that.

**Comment by ladyada** [comment]
ok cool! please submit that the best ya can - and we'll review em together :)

**Comment by afp316** [comment]
great! will try to get thru asap. appreciate the support!

y'all are so awesome!

**Comment by tyeth** [comment]
Thanks for this original work @afp316 - it's available in the latest release of wippersnapper (beta 82):
image

**Pull request closed without merging**
