### PR TITLE
Add VL53L0X I2C Component

### PR DESCRIPTION
**Pull request by afp316**

### CODE REVIEW

**Comment by brentru** [comment]
@afp316  Thank you for this pull request. Are you going to add an I2C component for the VL530L0X to the WipperSnapper Arduino firmware? (we have guide pages for this here - https://learn.adafruit.com/how-to-add-a-new-component-to-adafruit-io-wippersnapper/adding-an-i2c-component)

**Comment by afp316** [comment]
Of course! I plan to add it to the wiipersnapper arduino per the guide
pages you referenced. Looking to get the compensation added as an option in
wippersnapper by y'all so that I can confirm that it actually works.

Aaron

**Comment by brentru** [comment]
>  Looking to get the compensation added as an option in wippersnapper by y'all so that I can confirm that it actually works.

Not sure what you're referring to, the sensor's compensation?

**Comment by afp316** [comment]
My apologies, that was a typo on my part. I meant to say "component", as in
something that can be selected in the wippersnapper i2c components.   I
plan to do the VL53L4CD as well.

**Comment by brentru** [comment]
@afp316 Great, thanks for adding that. Please tag in me in your Adafruit WipperSnapper firmware PR and I'll be happy to review! Merging this in and making it live on Adafruit IO so you can test.

**Comment by brentru** [comment]
>  I'll try to capture what I changed and submit to you as soon as I can but it might be a few days.
Great, thank you!

>  There's one thing I might need assistance with though regarding using multiple of the same sensor
Since there is no jumper on the VL53L0X breakout, you'd need to use an I2C multiplexer.

**Comment by afp316** [comment]
I apologize, Brent.  I've been slacking; work has been crazy. I'm hoping to
get the PR to you this weekend.

**Comment by brentru** [comment]
@afp316  No problem!

**Pull request merged**
